// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHUlkT6y3h9gEShd_qtGo2xB4V7veJB8M',
    appId: '1:865833824680:web:27734a01c310f4fec7ad9d',
    messagingSenderId: '865833824680',
    projectId: 'xtap-570bb',
    authDomain: 'xtap-570bb.firebaseapp.com',
    storageBucket: 'xtap-570bb.firebasestorage.app',
    measurementId: 'G-8S84GY6WT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjmcABEw_3MwgvUKFSVzBKOyfGggUzd40',
    appId: '1:865833824680:android:7c1bb4f34e941387c7ad9d',
    messagingSenderId: '865833824680',
    projectId: 'xtap-570bb',
    storageBucket: 'xtap-570bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYTCol3V_xt6P-T8xpvcQD97nxEK3qac',
    appId: '1:865833824680:ios:ef7425571584010ac7ad9d',
    messagingSenderId: '865833824680',
    projectId: 'xtap-570bb',
    storageBucket: 'xtap-570bb.firebasestorage.app',
    iosBundleId: 'com.example.sqliteCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpYTCol3V_xt6P-T8xpvcQD97nxEK3qac',
    appId: '1:865833824680:ios:ef7425571584010ac7ad9d',
    messagingSenderId: '865833824680',
    projectId: 'xtap-570bb',
    storageBucket: 'xtap-570bb.firebasestorage.app',
    iosBundleId: 'com.example.sqliteCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHUlkT6y3h9gEShd_qtGo2xB4V7veJB8M',
    appId: '1:865833824680:web:9ba784d0065f21dac7ad9d',
    messagingSenderId: '865833824680',
    projectId: 'xtap-570bb',
    authDomain: 'xtap-570bb.firebaseapp.com',
    storageBucket: 'xtap-570bb.firebasestorage.app',
    measurementId: 'G-WFCGJLPJFS',
  );

}


